travis:
  secure:
    BINSTAR_TOKEN: CxHzFIN9LzRYNzWEP3gHQNriK3zKRGX6DcMuVkw8iuXvJcvp15iuylSisE8uwHhaYsodh/6RJ4OnqVC2BGAPdKxUtNKr/G/+WFqYJzv5U60OmaOfSXBI3kqMIKKCX7FLY8y5gERyY9PslOqnCPsNFkQU6KeLBb9aUxleX0fAznwUyDSB5JoKO/ytoBEJfnOwxDiAeA8MoOnvDAABslMasATQFIoGzn4bLckjEaVcwXmKnw61HyCYudticyvSYId/lY4gv50+0fP76LmYhE0MfqzaWlj3Z7kxpA/3xrF89V34uHkm+fxy15izcWRpp/oyn0ylDbSbOeNrKZUSnSqrTCCeaDt2MhCFPyYvBe+/zU48e52XPNf268hLwp7/PqAvZOk6qZvny607vEUfazBhnObWU9c7p9vTVRB9BBXg1dIc0H4sPOx9jAi4pHms5n+De1BgmyWTIYT1EQ7TtNwixrDHUap3OqLL2/dVqExQYZgoWhFdniGDh0wYNKNkc9QyR5Pk8cIEjmBWuVXSgaEyHftxEeksEq3FJKr4GAlIaPu5u4i02yTF2lnuJuvIoLSdrBqDLY23t/Yxe7Xzy2SGPJN/nSI1jeUI0J+2+mPbVKD66uHhnONBmMhdgfYLiH2JIVS0pw0OEmhQ91usSUB6BGY3QiX4d74coJQTe+VXjOs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
